name: " New feature request"
description: Suggest an idea for this project
title: 'feat: '
labels:
  - 'type: feature request'
body:
  - type: markdown
    attributes:
      value: |
        **Before You Start...**

        This form is only for submitting feature requests.

        Also try to search for your issue - it may have already been asked or even implemented in the main branch.
        However, if you find that an old, closed issue still persists in the latest version,
        you should open a new issue using the form below instead of commenting on the old issue.
  - type: textarea
    id: problem-description
    attributes:
      label: What problem does this feature solve?
      description: |
        Explain your use case, context, and rationale behind this feature request. More importantly, what is the **end user experience** you are trying to build that led to the need for this feature?
      placeholder: Problem description
    validations:
      required: true
  - type: textarea
    id: proposed-code
    attributes:
      label: How would you implement this feature?
      description: |
        Describe how you propose to solve the problem and provide code/api samples to use as guide. Note that you can use [Markdown](https://guides.github.com/features/mastering-markdown/) to format your code blocks.
      placeholder: Steps to reproduce
    validations:
      required: true
